"""
Industry configurations: companies, dimensions, mock data.
Each industry has its own companies, dimensions, and pre-computed scores/insights.
"""

INDUSTRIES = [
    "crm", "food-delivery", "ride-sharing", "saas",
    "e-commerce", "restaurants", "hospitality", "banking",
    "healthcare", "travel", "telecom", "insurance",
]

INDUSTRY_CONFIG = {
    "crm": {
        "name": "CRM Software",
        "focal": "HubSpot",
        "companies": ["HubSpot", "Salesforce", "Pipedrive", "Zoho CRM"],
        "dimensions": {
            "ease_of_use": "Ease of Use",
            "feature_richness": "Feature Richness",
            "customer_support": "Customer Support",
            "integrations": "Integrations",
            "value_for_money": "Value for Money",
            "reporting_analytics": "Reporting & Analytics",
        },
        "colors": {
            "HubSpot": "#FF7A59",
            "Salesforce": "#00BEFF",
            "Pipedrive": "#00D68F",
            "Zoho CRM": "#FF4D6A",
        },
        "mock_scores": {
            "HubSpot": {"ease_of_use": 78, "feature_richness": 72, "customer_support": 65,
                        "integrations": 80, "value_for_money": 58, "reporting_analytics": 70},
            "Salesforce": {"ease_of_use": 48, "feature_richness": 92, "customer_support": 62,
                          "integrations": 95, "value_for_money": 38, "reporting_analytics": 88},
            "Pipedrive": {"ease_of_use": 88, "feature_richness": 65, "customer_support": 75,
                         "integrations": 72, "value_for_money": 78, "reporting_analytics": 65},
            "Zoho CRM": {"ease_of_use": 62, "feature_richness": 82, "customer_support": 55,
                        "integrations": 75, "value_for_money": 82, "reporting_analytics": 70},
        },
        "data_file": "data/sample_reviews.json",
    },
    "food-delivery": {
        "name": "Food Delivery",
        "focal": "DoorDash",
        "companies": ["Uber Eats", "DoorDash", "Grubhub", "Deliveroo", "Just Eat"],
        "dimensions": {
            "delivery_speed": "Delivery Speed",
            "food_quality": "Food Quality",
            "app_experience": "App Experience",
            "restaurant_selection": "Restaurant Selection",
            "customer_support": "Customer Support",
            "pricing_fees": "Pricing & Fees",
        },
        "colors": {
            "Uber Eats": "#06C167",
            "DoorDash": "#FF3008",
            "Grubhub": "#F63440",
            "Deliveroo": "#00CCBC",
            "Just Eat": "#FF8000",
        },
        "mock_scores": {
            "Uber Eats": {"delivery_speed": 82, "food_quality": 78, "app_experience": 86,
                         "restaurant_selection": 88, "customer_support": 72, "pricing_fees": 58},
            "DoorDash": {"delivery_speed": 85, "food_quality": 76, "app_experience": 84,
                        "restaurant_selection": 90, "customer_support": 68, "pricing_fees": 60},
            "Grubhub": {"delivery_speed": 68, "food_quality": 72, "app_experience": 65,
                       "restaurant_selection": 78, "customer_support": 58, "pricing_fees": 65},
            "Deliveroo": {"delivery_speed": 88, "food_quality": 82, "app_experience": 80,
                         "restaurant_selection": 75, "customer_support": 75, "pricing_fees": 62},
            "Just Eat": {"delivery_speed": 70, "food_quality": 74, "app_experience": 68,
                        "restaurant_selection": 82, "customer_support": 62, "pricing_fees": 72},
        },
        "data_file": "data/sample_reviews_food.json",
    },
    "ride-sharing": {
        "name": "Ride-Sharing",
        "focal": "Uber",
        "companies": ["Uber", "Lyft", "Bolt", "FreeNow", "DiDi"],
        "dimensions": {
            "wait_time": "Wait Time",
            "driver_quality": "Driver Quality",
            "safety_features": "Safety Features",
            "pricing_transparency": "Pricing Transparency",
            "app_reliability": "App Reliability",
            "payment_options": "Payment Options",
        },
        "colors": {
            "Uber": "#000000",
            "Lyft": "#FF00BF",
            "Bolt": "#34D186",
            "FreeNow": "#FFC933",
            "DiDi": "#FF7426",
        },
        "mock_scores": {
            "Uber": {"wait_time": 85, "driver_quality": 78, "safety_features": 88,
                     "pricing_transparency": 65, "app_reliability": 82, "payment_options": 90},
            "Lyft": {"wait_time": 82, "driver_quality": 82, "safety_features": 86,
                     "pricing_transparency": 68, "app_reliability": 80, "payment_options": 85},
            "Bolt": {"wait_time": 88, "driver_quality": 85, "safety_features": 82,
                     "pricing_transparency": 82, "app_reliability": 78, "payment_options": 80},
            "FreeNow": {"wait_time": 75, "driver_quality": 76, "safety_features": 80,
                       "pricing_transparency": 72, "app_reliability": 74, "payment_options": 82},
            "DiDi": {"wait_time": 78, "driver_quality": 72, "safety_features": 75,
                     "pricing_transparency": 70, "app_reliability": 76, "payment_options": 88},
        },
        "data_file": "data/sample_reviews_ride.json",
    },
    "saas": {
        "name": "SaaS Collaboration",
        "focal": "Slack",
        "companies": ["Slack", "Microsoft Teams", "Zoom", "Discord", "Webex"],
        "dimensions": {
            "ease_of_use": "Ease of Use",
            "video_quality": "Video Quality",
            "integration_ecosystem": "Integration Ecosystem",
            "enterprise_security": "Enterprise Security",
            "mobile_experience": "Mobile Experience",
            "pricing_value": "Pricing Value",
        },
        "colors": {
            "Slack": "#4A154B",
            "Microsoft Teams": "#5059C9",
            "Zoom": "#2D8CFF",
            "Discord": "#5865F2",
            "Webex": "#00BCEB",
        },
        "mock_scores": {
            "Slack": {"ease_of_use": 92, "video_quality": 78, "integration_ecosystem": 95,
                      "enterprise_security": 88, "mobile_experience": 88, "pricing_value": 72},
            "Microsoft Teams": {"ease_of_use": 75, "video_quality": 82, "integration_ecosystem": 88,
                               "enterprise_security": 92, "mobile_experience": 72, "pricing_value": 85},
            "Zoom": {"ease_of_use": 90, "video_quality": 95, "integration_ecosystem": 75,
                     "enterprise_security": 85, "mobile_experience": 85, "pricing_value": 78},
            "Discord": {"ease_of_use": 88, "video_quality": 85, "integration_ecosystem": 72,
                       "enterprise_security": 65, "mobile_experience": 90, "pricing_value": 95},
            "Webex": {"ease_of_use": 68, "video_quality": 80, "integration_ecosystem": 78,
                      "enterprise_security": 90, "mobile_experience": 70, "pricing_value": 70},
        },
        "data_file": "data/sample_reviews_saas.json",
    },
    "e-commerce": {
        "name": "E-Commerce",
        "focal": "Amazon",
        "companies": ["Amazon", "Shopify", "eBay"],
        "dimensions": {
            "product_quality": "Product Quality",
            "delivery_speed": "Delivery Speed",
            "customer_support": "Customer Support",
            "pricing_value": "Pricing & Value",
            "ease_of_use": "Ease of Use",
            "return_process": "Return Process",
        },
        "colors": {
            "Amazon": "#FF9900",
            "Shopify": "#96BF48",
            "eBay": "#E53238",
        },
        "mock_scores": {
            "Amazon": {"product_quality": 78, "delivery_speed": 92, "customer_support": 62,
                       "pricing_value": 75, "ease_of_use": 88, "return_process": 72},
            "Shopify": {"product_quality": 82, "delivery_speed": 70, "customer_support": 78,
                        "pricing_value": 68, "ease_of_use": 85, "return_process": 75},
            "eBay": {"product_quality": 72, "delivery_speed": 68, "customer_support": 58,
                     "pricing_value": 82, "ease_of_use": 70, "return_process": 65},
        },
        "data_file": "data/sample_reviews_ecommerce.json",
    },
    "restaurants": {
        "name": "Restaurants & Hospitality",
        "focal": "McDonald's",
        "companies": ["McDonald's", "Starbucks", "Chipotle", "Subway", "Domino's"],
        "dimensions": {
            "food_quality": "Food Quality",
            "service_speed": "Service Speed",
            "value_for_money": "Value for Money",
            "cleanliness": "Cleanliness",
            "customer_service": "Customer Service",
            "menu_variety": "Menu Variety",
        },
        "colors": {
            "McDonald's": "#FFC72C",
            "Starbucks": "#00704A",
            "Chipotle": "#9D4B00",
            "Subway": "#00853D",
            "Domino's": "#E31837",
        },
        "mock_scores": {
            "McDonald's": {"food_quality": 68, "service_speed": 85, "value_for_money": 82,
                          "cleanliness": 75, "customer_service": 62, "menu_variety": 78},
            "Starbucks": {"food_quality": 75, "service_speed": 70, "value_for_money": 58,
                         "cleanliness": 88, "customer_service": 78, "menu_variety": 85},
            "Chipotle": {"food_quality": 85, "service_speed": 72, "value_for_money": 75,
                        "cleanliness": 80, "customer_service": 75, "menu_variety": 68},
            "Subway": {"food_quality": 65, "service_speed": 78, "value_for_money": 82,
                      "cleanliness": 72, "customer_service": 68, "menu_variety": 88},
            "Domino's": {"food_quality": 72, "service_speed": 90, "value_for_money": 78,
                        "cleanliness": 75, "customer_service": 72, "menu_variety": 70},
        },
        "data_file": "data/sample_reviews_restaurants.json",
    },
    "hospitality": {
        "name": "Restaurants & Hospitality Platforms",
        "focal": "Yelp",
        "companies": ["Yelp", "TripAdvisor", "OpenTable"],
        "dimensions": {
            "ease_of_use": "Ease of Use",
            "review_quality": "Review Quality",
            "restaurant_coverage": "Restaurant Coverage",
            "booking_experience": "Booking Experience",
            "customer_support": "Customer Support",
            "value_for_money": "Value for Money",
        },
        "colors": {
            "Yelp": "#D32323",
            "TripAdvisor": "#00AF87",
            "OpenTable": "#DA3743",
        },
        "mock_scores": {
            "Yelp": {"ease_of_use": 85, "review_quality": 88, "restaurant_coverage": 92,
                     "booking_experience": 65, "customer_support": 70, "value_for_money": 82},
            "TripAdvisor": {"ease_of_use": 78, "review_quality": 85, "restaurant_coverage": 95,
                            "booking_experience": 72, "customer_support": 68, "value_for_money": 75},
            "OpenTable": {"ease_of_use": 90, "review_quality": 72, "restaurant_coverage": 78,
                          "booking_experience": 95, "customer_support": 75, "value_for_money": 70},
        },
        "data_file": "data/sample_reviews_hospitality.json",
    },
    "banking": {
        "name": "Digital Banking & Fintech",
        "focal": "Revolut",
        "companies": ["Revolut", "N26", "Chime"],
        "dimensions": {
            "ease_of_use": "Ease of Use",
            "fees_transparency": "Fees & Transparency",
            "customer_support": "Customer Support",
            "security_trust": "Security & Trust",
            "features": "Features & Tools",
            "international_transfers": "International Transfers",
        },
        "colors": {
            "Revolut": "#0075EB",
            "N26": "#48AC98",
            "Chime": "#00D9A5",
        },
        "mock_scores": {
            "Revolut": {"ease_of_use": 88, "fees_transparency": 72, "customer_support": 58,
                       "security_trust": 82, "features": 90, "international_transfers": 92},
            "N26": {"ease_of_use": 85, "fees_transparency": 78, "customer_support": 62,
                   "security_trust": 85, "features": 75, "international_transfers": 78},
            "Chime": {"ease_of_use": 82, "fees_transparency": 88, "customer_support": 65,
                     "security_trust": 80, "features": 68, "international_transfers": 55},
        },
        "data_file": "data/sample_reviews_banking.json",
    },
    "healthcare": {
        "name": "Healthcare",
        "focal": "Zocdoc",
        "companies": ["Zocdoc", "Healthgrades", "WebMD"],
        "dimensions": {
            "ease_of_use": "Ease of Use",
            "doctor_availability": "Doctor Availability",
            "booking_experience": "Booking Experience",
            "review_trust": "Review Trust",
            "customer_support": "Customer Support",
            "value_for_money": "Value for Money",
        },
        "colors": {
            "Zocdoc": "#00A3E0",
            "Healthgrades": "#0066CC",
            "WebMD": "#00A878",
        },
        "mock_scores": {
            "Zocdoc": {"ease_of_use": 88, "doctor_availability": 85, "booking_experience": 90,
                       "review_trust": 75, "customer_support": 72, "value_for_money": 80},
            "Healthgrades": {"ease_of_use": 75, "doctor_availability": 92, "booking_experience": 65,
                             "review_trust": 88, "customer_support": 68, "value_for_money": 78},
            "WebMD": {"ease_of_use": 82, "doctor_availability": 70, "booking_experience": 55,
                      "review_trust": 85, "customer_support": 65, "value_for_money": 85},
        },
        "data_file": "data/sample_reviews_healthcare.json",
    },
    "travel": {
        "name": "Travel",
        "focal": "Booking",
        "companies": ["Booking.com", "Airbnb", "Expedia"],
        "dimensions": {
            "ease_of_use": "Ease of Use",
            "price_transparency": "Price Transparency",
            "customer_support": "Customer Support",
            "property_quality": "Property Quality",
            "cancellation_policy": "Cancellation Policy",
            "value_for_money": "Value for Money",
        },
        "colors": {
            "Booking.com": "#003580",
            "Airbnb": "#FF5A5F",
            "Expedia": "#FFCB00",
        },
        "mock_scores": {
            "Booking.com": {"ease_of_use": 85, "price_transparency": 72, "customer_support": 75,
                           "property_quality": 88, "cancellation_policy": 80, "value_for_money": 82},
            "Airbnb": {"ease_of_use": 90, "price_transparency": 65, "customer_support": 62,
                       "property_quality": 85, "cancellation_policy": 70, "value_for_money": 78},
            "Expedia": {"ease_of_use": 78, "price_transparency": 75, "customer_support": 70,
                        "property_quality": 82, "cancellation_policy": 78, "value_for_money": 80},
        },
        "data_file": "data/sample_reviews_travel.json",
    },
    "telecom": {
        "name": "Telecom",
        "focal": "Vodafone",
        "companies": ["Vodafone", "Verizon", "AT&T"],
        "dimensions": {
            "network_quality": "Network Quality",
            "customer_support": "Customer Support",
            "pricing_transparency": "Pricing Transparency",
            "coverage": "Coverage",
            "value_for_money": "Value for Money",
            "ease_of_use": "Ease of Use",
        },
        "colors": {
            "Vodafone": "#E60000",
            "Verizon": "#CD040B",
            "AT&T": "#00A8E0",
        },
        "mock_scores": {
            "Vodafone": {"network_quality": 82, "customer_support": 65, "pricing_transparency": 68,
                         "coverage": 85, "value_for_money": 72, "ease_of_use": 78},
            "Verizon": {"network_quality": 92, "customer_support": 70, "pricing_transparency": 62,
                        "coverage": 95, "value_for_money": 65, "ease_of_use": 75},
            "AT&T": {"network_quality": 85, "customer_support": 68, "pricing_transparency": 65,
                     "coverage": 88, "value_for_money": 70, "ease_of_use": 80},
        },
        "data_file": "data/sample_reviews_telecom.json",
    },
    "insurance": {
        "name": "Insurance",
        "focal": "Lemonade",
        "companies": ["Lemonade", "Geico", "Allstate"],
        "dimensions": {
            "ease_of_use": "Ease of Use",
            "claims_process": "Claims Process",
            "pricing_transparency": "Pricing Transparency",
            "customer_support": "Customer Support",
            "coverage_options": "Coverage Options",
            "value_for_money": "Value for Money",
        },
        "colors": {
            "Lemonade": "#7C3AED",
            "Geico": "#0066B3",
            "Allstate": "#003366",
        },
        "mock_scores": {
            "Lemonade": {"ease_of_use": 95, "claims_process": 88, "pricing_transparency": 90,
                         "customer_support": 82, "coverage_options": 65, "value_for_money": 85},
            "Geico": {"ease_of_use": 85, "claims_process": 78, "pricing_transparency": 75,
                      "customer_support": 72, "coverage_options": 88, "value_for_money": 82},
            "Allstate": {"ease_of_use": 72, "claims_process": 75, "pricing_transparency": 68,
                         "customer_support": 78, "coverage_options": 92, "value_for_money": 75},
        },
        "data_file": "data/sample_reviews_insurance.json",
    },
}

# Mock insights per industry (used when no API / mock mode)
MOCK_INSIGHTS_BY_INDUSTRY = {
    "crm": [
        {"title": "Pricing Pressure Is HubSpot's Biggest Structural Risk", "body": "Value for money scores declined from 68 -> 58 over six quarters.", "audience": "Companies", "confidence": "High", "action": "Audit pricing tier structure for SMB buyers."},
        {"title": "Customer Support Is the Category's Unclaimed Whitespace", "body": "No player scores above 75/100 on support.", "audience": "Investors", "confidence": "High", "action": "Support-first challengers deserve a premium multiple."},
        {"title": "Pipedrive's Review Volume Signals Word-of-Mouth Inflection", "body": "Review volume up 23% YoY vs HubSpot's 11%.", "audience": "Investors", "confidence": "Medium", "action": "Model Pipedrive cannibalising 5-8% of HubSpot SMB adds."},
        {"title": "Salesforce's Mid-Market Churn Signal Is Elevated", "body": "Churn mentions grew 18% QoQ for Salesforce.", "audience": "Companies", "confidence": "Medium", "action": "Launch 'Salesforce Simplifier' migration campaign."},
        {"title": "Value Decline Is a Category Signal", "body": "Average value-for-money fell 72 -> 64 across all players.", "audience": "Investors", "confidence": "High", "action": "Watch for usage-based pricing CRM entrants."},
    ],
    "food-delivery": [
        {"title": "DoorDash Market Leadership", "body": "DoorDash maintains highest review volume and strong restaurant selection (90/100).", "audience": "Investors", "confidence": "High", "action": "Monitor DoorDash's margin trajectory vs Uber Eats."},
        {"title": "Customer Support Vulnerability", "body": "All players score below 75/100 on support. Grubhub at critical 58/100.", "audience": "Investors", "confidence": "High", "action": "Support-first delivery platforms could capture margin."},
        {"title": "Deliveroo Sentiment Momentum", "body": "Deliveroo shows +7% QoQ sentiment growth despite mid-tier pricing.", "audience": "Investors", "confidence": "Medium", "action": "Track Deliveroo's expansion in key markets."},
        {"title": "Customer Support Gap", "body": "Industry-wide weakness in support. Top complaints: refund delays, driver communication.", "audience": "Companies", "confidence": "High", "action": "Invest in support to differentiate."},
        {"title": "Pricing Power Compression", "body": "Pricing & Fees shows lowest satisfaction (avg 63/100).", "audience": "Companies", "confidence": "High", "action": "Improve fee transparency."},
    ],
    "ride-sharing": [
        {"title": "Bolt Value Proposition", "body": "Bolt achieves 48% sentiment at 20% lower price than Uber.", "audience": "Investors", "confidence": "High", "action": "Model Bolt's unit economics in price-sensitive segments."},
        {"title": "Pricing Transparency Crisis", "body": "Uber and Lyft score below 70/100 on pricing transparency.", "audience": "Investors", "confidence": "High", "action": "Regulatory risk as surge pricing scrutiny increases."},
        {"title": "Safety as Competitive Moat", "body": "Safety features now top priority (96/100 importance). Uber leads at 88/100.", "audience": "Investors", "confidence": "Medium", "action": "Monitor safety investment across players."},
        {"title": "Pricing Transparency Whitespace", "body": "Bolt leads (82/100) while Uber/Lyft lag (65-68/100).", "audience": "Companies", "confidence": "High", "action": "Upfront no-surge pricing could capture frustrated customers."},
        {"title": "Best for Safety: Uber", "body": "Uber offers most comprehensive safety features (88/100).", "audience": "Customers", "confidence": "High", "action": "Highlight safety in marketing."},
    ],
    "saas": [
        {"title": "Discord Community Monetization", "body": "Discord achieves 68% sentiment at lowest price with 125K reviews.", "audience": "Investors", "confidence": "High", "action": "Model Discord's viral growth and monetization."},
        {"title": "Microsoft Teams Enterprise Lock-in", "body": "Teams scores 92/100 on security with bundled M365 pricing advantage.", "audience": "Investors", "confidence": "High", "action": "Monitor Teams' share in enterprise."},
        {"title": "Integration Ecosystem as Moat", "body": "Slack's integration lead (95/100) creates switching costs.", "audience": "Investors", "confidence": "High", "action": "Track Slack's app directory growth."},
        {"title": "Mobile Experience Gap", "body": "Discord leads mobile (90/100) while Teams lags (72/100).", "audience": "Companies", "confidence": "High", "action": "Invest in mobile-first design."},
        {"title": "Best for Teams: Slack", "body": "Slack offers 92/100 usability, 95/100 integrations.", "audience": "Customers", "confidence": "High", "action": "Compare Slack vs Teams for your use case."},
    ],
    "e-commerce": [
        {"title": "Amazon Delivery Moat", "body": "Amazon leads delivery speed (92/100) while others lag. Same-day/next-day is table stakes.", "audience": "Investors", "confidence": "High", "action": "Monitor Amazon's logistics capex vs competitors."},
        {"title": "Shopify Quality Premium", "body": "Shopify scores 82/100 on product quality — strong for SMB sellers. Platform flexibility drives loyalty.", "audience": "Investors", "confidence": "High", "action": "Track Shopify's take rate vs marketplaces."},
        {"title": "Support Gap Across E-Commerce", "body": "No player scores above 78/100 on customer support. Returns and disputes are pain points.", "audience": "Companies", "confidence": "High", "action": "Invest in support to reduce churn."},
        {"title": "eBay Value Proposition", "body": "eBay scores 82/100 on value. Strong for used and unique items.", "audience": "Customers", "confidence": "High", "action": "Compare eBay vs Amazon for marketplace purchases."},
        {"title": "eBay Marketplace Dynamics", "body": "eBay scores 82/100 on value but 58/100 on support. Seller experience drives platform health.", "audience": "Investors", "confidence": "Medium", "action": "Watch eBay's seller fee changes."},
    ],
    "restaurants": [
        {"title": "Chipotle Food Quality Lead", "body": "Chipotle scores 85/100 on food quality — highest in fast casual. Fresh ingredients resonate.", "audience": "Investors", "confidence": "High", "action": "Model Chipotle's unit economics vs QSR peers."},
        {"title": "Domino's Speed Advantage", "body": "Domino's leads service speed (90/100). Delivery tech is a moat.", "audience": "Investors", "confidence": "High", "action": "Track Domino's delivery time metrics."},
        {"title": "Starbucks Premium Positioning", "body": "Starbucks scores 58/100 on value but 88/100 on cleanliness. Premium experience sustains margins.", "audience": "Companies", "confidence": "High", "action": "Balance premium pricing with value perception."},
        {"title": "Subway Menu Variety", "body": "Subway leads menu variety (88/100) but lags on food quality (65/100). Customization is key differentiator.", "audience": "Companies", "confidence": "Medium", "action": "Improve ingredient quality to match variety."},
        {"title": "Best Value: McDonald's", "body": "McDonald's scores 82/100 on value. Consistent and affordable.", "audience": "Customers", "confidence": "High", "action": "McDonald's for budget-friendly meals."},
    ],
    "banking": [
        {"title": "Revolut Feature Lead", "body": "Revolut scores 90/100 on features — crypto, stocks, multi-currency. Support lags at 58/100.", "audience": "Investors", "confidence": "High", "action": "Monitor Revolut's support investment."},
        {"title": "Chime Fee Transparency", "body": "Chime leads fees transparency (88/100). No-fee model resonates with underbanked.", "audience": "Companies", "confidence": "High", "action": "Emulate fee transparency in product design."},
        {"title": "N26 Balanced Profile", "body": "N26 balances features, transparency, and support. Strong EU positioning.", "audience": "Investors", "confidence": "Medium", "action": "Track N26's expansion in key markets."},
        {"title": "Revolut Support Vulnerability", "body": "Revolut scores 58/100 on support despite 90/100 on features. Scale without support hurts retention.", "audience": "Investors", "confidence": "High", "action": "Invest in support to reduce churn."},
        {"title": "Best for Fees: Chime", "body": "Chime offers 88/100 on fee transparency. No hidden charges.", "audience": "Customers", "confidence": "High", "action": "Chime for fee-conscious banking."},
    ],
    "hospitality": [
        {"title": "Yelp Restaurant Coverage Lead", "body": "Yelp scores 92/100 on restaurant coverage. Strong local discovery dominance.", "audience": "Investors", "confidence": "High", "action": "Monitor Yelp's local ad revenue growth."},
        {"title": "OpenTable Booking Experience", "body": "OpenTable leads booking experience (95/100) but lags on review quality (72/100).", "audience": "Companies", "confidence": "High", "action": "OpenTable for restaurant reservations."},
        {"title": "TripAdvisor Review Trust", "body": "TripAdvisor scores 88/100 on review trust. Travel-focused content differentiates.", "audience": "Investors", "confidence": "Medium", "action": "Track TripAdvisor's review authenticity efforts."},
        {"title": "Yelp vs TripAdvisor", "body": "Yelp leads local coverage; TripAdvisor leads travel. Different use cases.", "audience": "Customers", "confidence": "High", "action": "Compare by use case: local vs travel."},
        {"title": "Hospitality Platform Consolidation", "body": "Booking experience scores vary 65-95. Integration opportunity for restaurants.", "audience": "Companies", "confidence": "Medium", "action": "Evaluate multi-platform presence."},
    ],
    "healthcare": [
        {"title": "Zocdoc Booking Experience", "body": "Zocdoc leads booking experience (90/100). Ease of use drives patient acquisition.", "audience": "Investors", "confidence": "High", "action": "Monitor Zocdoc's booking conversion rates."},
        {"title": "Healthgrades Doctor Availability", "body": "Healthgrades scores 92/100 on doctor availability. Largest provider database.", "audience": "Investors", "confidence": "High", "action": "Track Healthgrades' provider network growth."},
        {"title": "WebMD Content Trust", "body": "WebMD scores 85/100 on review trust. Health content drives engagement.", "audience": "Companies", "confidence": "Medium", "action": "Leverage WebMD for patient education."},
        {"title": "Healthcare Support Gap", "body": "No platform scores above 72/100 on support. Critical for patient experience.", "audience": "Companies", "confidence": "High", "action": "Invest in support for healthcare platforms."},
        {"title": "Best for Booking: Zocdoc", "body": "Zocdoc offers 90/100 on booking. Easiest way to find and book doctors.", "audience": "Customers", "confidence": "High", "action": "Use Zocdoc for doctor appointments."},
    ],
    "travel": [
        {"title": "Booking.com Property Quality", "body": "Booking.com leads property quality (88/100). Hotel inventory is moat.", "audience": "Investors", "confidence": "High", "action": "Monitor Booking's hotel supply growth."},
        {"title": "Airbnb UX Advantage", "body": "Airbnb scores 90/100 on ease of use. Host-guest model differentiates.", "audience": "Investors", "confidence": "High", "action": "Track Airbnb's experience expansion."},
        {"title": "Expedia Price Transparency", "body": "Expedia leads price transparency (75/100). Bundles drive value.", "audience": "Companies", "confidence": "Medium", "action": "Compare Expedia bundles vs competitors."},
        {"title": "Travel Support Gap", "body": "Airbnb scores 62/100 on support. Cancellation disputes are pain point.", "audience": "Companies", "confidence": "High", "action": "Improve support for dispute resolution."},
        {"title": "Best for Hotels: Booking.com", "body": "Booking.com offers 88/100 on property quality. Best for hotels.", "audience": "Customers", "confidence": "High", "action": "Use Booking.com for hotel stays."},
    ],
    "telecom": [
        {"title": "Verizon Network Quality", "body": "Verizon leads network quality (92/100) and coverage (95/100). Premium positioning.", "audience": "Investors", "confidence": "High", "action": "Monitor Verizon's 5G deployment."},
        {"title": "Pricing Transparency Crisis", "body": "All players score below 70/100 on pricing transparency. Hidden fees are common.", "audience": "Companies", "confidence": "High", "action": "Simplify pricing to differentiate."},
        {"title": "Vodafone EU Coverage", "body": "Vodafone scores 85/100 on coverage. Strong EU presence.", "audience": "Investors", "confidence": "Medium", "action": "Track Vodafone's EU market share."},
        {"title": "AT&T Balanced Profile", "body": "AT&T balances network (85/100) and ease of use (80/100).", "audience": "Customers", "confidence": "High", "action": "Compare AT&T vs Verizon for your area."},
        {"title": "Telecom Support Gap", "body": "No player scores above 70/100 on support. Retention opportunity.", "audience": "Companies", "confidence": "High", "action": "Invest in support to reduce churn."},
    ],
    "insurance": [
        {"title": "Lemonade UX Disruption", "body": "Lemonade scores 95/100 on ease of use. AI-first claims differentiate.", "audience": "Investors", "confidence": "High", "action": "Model Lemonade's digital-first economics."},
        {"title": "Geico Coverage Options", "body": "Geico scores 88/100 on coverage options. Broad product portfolio.", "audience": "Investors", "confidence": "High", "action": "Track Geico's product expansion."},
        {"title": "Lemonade Claims Process", "body": "Lemonade leads claims process (88/100). Fast payouts drive NPS.", "audience": "Companies", "confidence": "High", "action": "Emulate Lemonade's claims UX."},
        {"title": "Allstate Traditional Strength", "body": "Allstate scores 92/100 on coverage. Agent network is moat.", "audience": "Investors", "confidence": "Medium", "action": "Track Allstate's digital transformation."},
        {"title": "Best for Digital: Lemonade", "body": "Lemonade offers 95/100 ease of use. Best for renters and simple policies.", "audience": "Customers", "confidence": "High", "action": "Compare Lemonade for renters insurance."},
    ],
}
